### ISSUE TITLE
'None'

### ISSUE THREAD

**Issue by paulin-mipt** [ErgyCJC/TicTacToe#3]
https://github.com/ErgyCJC/TicTacToe/blob/14af2e92e7fe94347b34251492201e2b9f218da0/dev_dir/tic-tac-toe.py#L149

Довольно странное место. Почему здесь строка?

**Comment by ErgyCJC** [comment]
Исковерканное 'noone'. check_win_state() возвращает имя победителя, если таковой имеется; 'noone' - результат ничьей, её условие было не на своем месте в этой функции.
